### ISSUE TITLE
Buy Package automatic linear progression between two entries

### ISSUE THREAD

**Issue by Araxiel** [Babylon-Development-Victoria-3/Victoria-3-dev-utilities#2]
**Is your feature request related to a problem?**
If wanting a need to ramp down or up, individual entries need to manually be modified.

**Describe the solution you'd like**
Let's say, we have `popneed_movies`. At `wealth_20` it's at 5, and at `wealth_30` it's at 10. Allow for example the selecting of the two boxes, and press a button and the tool will automatically fill the wealth levels in-between 20-30, with slowly increasing values. E.g:
Start with:
|  | goods.popneed_movies  |
|-----------|----|
| wealth_20 | 5  |
| wealth_21 |    |
| wealth_22 |    |
| wealth_23 |    |
| wealth_24 |    |
| wealth_25 |    |
| wealth_26 |    |
| wealth_27 |    |
| wealth_28 |    |
| wealth_29 |    |
| wealth_30 | 10 |

Select the 5 box and 10 box. Click button.

|  | goods.popneed_movies  |
|-----------|----|
| wealth_21 | 5.5 |
| wealth_22 | 6   |
| wealth_23 | 6.5 |
| wealth_24 | 7   |
| wealth_25 | 7.5 |
| wealth_26 | 8   |
| wealth_27 | 8.5 |
| wealth_28 | 9   |
| wealth_29 | 9.5 |
| wealth_30 | 10  |

Same thing in revers, if a need should go down.

**Comment by HiddeLekanne** [comment]
done
